### ISSUE TITLE
Media Query Team: Implement Responsiveness - Index page - All sections

### ISSUE THREAD

**Issue by benjaminskarding** [NoroffFEU/musikkforandrerliv.no#154]
### Implement Responsive Media Queries for Index Page
**(Excluding Header and Footer)**

**Objective:** 
Ensure all sections of the Index page are fully responsive and provide an optimal viewing experience across different devices and screen sizes.

**Tasks:**

- [ ] Define and apply media queries for Index page sections across mobile, tablet, and desktop.

- [ ] Adjust text, images, buttons, and other elements to ensure proper scaling and interaction.

- [ ] Test responsiveness and functionality across browsers and devices.

- [ ] Coordinate with the design team to ensure changes comply with the overall design vision.

- [ ] Follow QA dev rules

- [ ] Confirm alignment with existing responsive behaviors for the header and footer to ensure a cohesive page experience.

Desktop Starting View:
![Image](https://github.com/NoroffFEU/musikkforandrerliv.no/assets/127968874/532ecd8f-df1c-4043-873b-c62b20e84a67)
Mobile End View:
![Image](https://github.com/NoroffFEU/musikkforandrerliv.no/assets/127968874/8f27bfa9-53ef-49e3-b67b-fc07ef987188)

**Comment by cnnrbrn** [comment]
The status of this needs to be checked. If done, delete this task. If not, assign one or two devs.

**Comment by LauraKaraliene** [comment]
Hi, 
how should we divide the task for this issue? Should we each take specific parts or should we work together on certain areas? 
Not sure how it works when more than 1 person is assigned. 

- @stineknutsen 
- @taraolivia 

Thanks!

**Comment by Arkuradev** [comment]
> Hi, how should we divide the task for this issue? Should we each take specific parts or should we work together on certain areas? Not sure how it works when more than 1 person is assigned.
> 
> * [@stineknutsen](https://github.com/stineknutsen)
> * [@taraolivia](https://github.com/taraolivia)
> 
> Thanks!

Hey Laura. 
Good question! What I would think is best here is if you and Stine talk with eachother and agree upon who does what. On tasks where there is more than one person assigned they have to divide it up to smaller parts so you dont end up in a situation where both of you solve the same problem. 
Because in the end both of you will send your code back to Github which all ends up in the same place.
