### ISSUE TITLE
Set Design Checklist

### ISSUE THREAD

**Issue by Whisperpiano** [NoroffFEU/musikkforandrerliv.no#24]
## Design checklist
We created a document where we will write and set some rules for the design team. This document will serve as a guide to ensure that our designs meet the expectations of our client.

[Link to the word document](https://noroff.sharepoint.com/:w:/s/FED1-August2023Full-time2/ER7_onSEIaxAilRKPANFS98BgIgmjBu4DtqlTXefewhg9A?e=aqe5Fz)

- [x] Visual Hierarchy 
- [x] Layout
- [x] Consistency
- [x] Screen Size
- [x] Usability Principles 
- [x] WCAG - Web Content Accessibility Guidelines
- [x] Colors
- [x] Fonts 
- [x] Whitespace and Padding
- [x] Image Quality 
- [x] Iconography
- [x] Micro interactions 
- [x] Error States and Feedback 
- [x] Browser Compatibility 
- [x] Performance Optimization
- [x] Design Documentation
- [x] Exporting pictures, videos, vectors and icons
- [x] Share Document with Design Team
